# Site settings
title: Ms. S: Software Developer in the Making
header-img: img/home-bg.png
email: elysa.silveira@gmail.com
copyright_name: elysasilveira
description: > # this means to ignore newlines until "baseurl:"
  Working through Flatiron's Online Web Developer Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  elysasilveira
learn_profile: elysasilveira
email_username: elysa.silveira@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
